name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for hatch-vcs versioning

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,test]
        pip install build

    - name: Run linting
      run: |
        python -m ruff check src/boabro tests
        python -m ruff format --check src/boabro tests

    - name: Run type checking
      run: |
        python -m mypy src/boabro tests

    - name: Run tests
      run: |
        python -m pytest tests/ src/boabro/test_boabro.py -v --cov=src/boabro --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Build package
      run: |
        python -m build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.python-version }}
        path: dist/

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,test]
        npm install -g http-server

    - name: Start HTTP server
      run: |
        nohup http-server -p 8080 -c-1 &
        sleep 2

    - name: Test HTML examples
      run: |
        # Basic smoke test - check if examples load without errors
        curl -f http://localhost:8080/docs/pyscript-puepy-bootstrap.html > /dev/null
        curl -f http://localhost:8080/docs/pyscript-puepy-bulma.html > /dev/null
        curl -f http://localhost:8080/docs/gradio.html > /dev/null
        curl -f http://localhost:8080/docs/stlite.html > /dev/null
        echo "✅ HTML examples load successfully"